# Generated by Django 5.0.4 on 2024-06-14 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The only required field", max_length=90
                    ),
                ),
                ("composer", models.CharField(blank=True, max_length=30)),
                ("key", models.CharField(blank=True, max_length=10)),
                ("other_keys", models.CharField(blank=True, max_length=20)),
                (
                    "song_form",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AABA", "AABA"),
                            ("ABAC", "ABAC"),
                            ("ABA", "ABA"),
                            ("ABAB", "ABAB"),
                            ("ABCD", "ABCD"),
                            ("AB", "AB"),
                            ("AAB", "AAB"),
                            ("AABC", "AABC"),
                            ("blues", "blues"),
                            ("irregular", "irregular"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[("standard", "standard"), ("jazz", "jazz")],
                        default="standard",
                        max_length=15,
                    ),
                ),
                (
                    "meter",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (0, "irregular"),
                        ],
                        default=4,
                        null=True,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "is_contrafact",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RepertoireTune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_played", models.DateField(blank=True, null=True)),
                (
                    "knowledge",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("know", "know"),
                            ("learning", "learning"),
                            ("don't know", "don't know"),
                        ],
                        default="know",
                        max_length=15,
                    ),
                ),
                ("started_learning", models.DateTimeField(blank=True, null=True)),
                ("play_count", models.IntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jazztunes.tune"
                    ),
                ),
            ],
            options={
                "unique_together": {("tune", "player")},
            },
        ),
    ]
