# Generated by Django 5.0.4 on 2024-06-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jazztunes", "0004_alter_repertoiretune_last_played"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="repertoiretune",
            name="tags",
            field=models.ManyToManyField(
                related_name="repertoire_tunes", to="jazztunes.tag"
            ),
        ),
    ]
