# Generated by Django 5.0.4 on 2024-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jazztunes", "0005_tag_repertoiretune_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repertoiretune",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="repertoire_tunes", to="jazztunes.tag"
            ),
        ),
    ]
