# Generated by Django 5.2.11 on 2026-02-06 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jazztunes", "0007_alter_repertoiretune_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repertoiretune",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="repertoire_tunes", to="jazztunes.tag"
            ),
        ),
        migrations.AlterField(
            model_name="repertoiretune",
            name="tune",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jazztunes.tune"
            ),
        ),
    ]
