# Generated by Django 5.2.11 on 2026-02-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazztunes', '0008_alter_repertoiretune_tags_alter_repertoiretune_tune'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('repertoire_tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='jazztunes.repertoiretune')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
    ]
