# Generated by Django 5.2.11 on 2026-02-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jazztunes', '0010_migrate_last_played_to_plays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repertoiretune',
            name='last_played',
        ),
        migrations.RemoveField(
            model_name='repertoiretune',
            name='play_count',
        ),
    ]
