# Generated by Django 5.2.11 on 2026-02-13 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jazztunes", "0011_remove_repertoiretune_last_played_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="played_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 13, 14, 3, 13, 625889, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
