# Generated by Django 5.2.11 on 2026-02-13 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jazztunes", "0012_alter_play_played_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="played_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
