from decouple import config

# auth
USERNAME = config("TEST_USERNAME")
PASSWORD = config("TEST_PASSWORD")

# tune
SINGLE_TUNE_TITLE = "Yesterday's Tomorrows"
SINGLE_TUNE_COMPOSER = "Belderbos"
SINGLE_TUNE_KEY = "C"
SINGLE_TUNE_OTHER_KEYS = "F D-"
SINGLE_TUNE_FORM = "AABA"
SINGLE_TUNE_STYLE = "standard"
SINGLE_TUNE_METER = 4
SINGLE_TUNE_YEAR = "2024"
SINGLE_TUNE_TAGS = None
SINGLE_TUNE_KNOWLEDGE = "learning"
SINGLE_TUNE_LAST_PLAYED = "2025-06-17"
SINGLE_TUNE_LAST_PLAYED_DISPLAY = "June 17"
DATE_DISPLAY_FORMAT = "%B %d"
