# Generated by Django 4.2.7 on 2023-11-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("composer", models.CharField(blank=True, max_length=30)),
                ("key", models.CharField(blank=True, max_length=10)),
                ("other_keys", models.CharField(blank=True, max_length=20)),
                ("song_form", models.CharField(blank=True, max_length=20)),
                ("style", models.CharField(blank=True, max_length=20)),
                ("meter", models.CharField(blank=True, max_length=10)),
                ("year", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
