# Generated by Django 5.0.4 on 2024-06-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0002_alter_tune_meter_alter_tune_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tune",
            name="meter",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (0, "irregular"),
                ],
                default=4,
                null=True,
            ),
        ),
    ]
