# Generated by Django 5.0.4 on 2024-06-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0003_alter_tune_meter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repertoiretune",
            name="last_played",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
