# Generated by Django 4.2.7 on 2023-11-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune', '0003_alter_tune_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='key',
            field=models.CharField(blank=True, help_text='One only, use single letter for major, add - for minor', max_length=10),
        ),
        migrations.AlterField(
            model_name='tune',
            name='other_keys',
            field=models.CharField(blank=True, help_text='As many as you want, separated by a space', max_length=20),
        ),
    ]
