# Generated by Django 4.2.7 on 2023-11-29 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0006_alter_tune_players"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tune",
            name="players",
        ),
    ]
