# Generated by Django 5.0.4 on 2024-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0006_alter_repertoiretune_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repertoiretune",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="ctrl-click to select more than one",
                related_name="repertoire_tunes",
                to="tune.tag",
            ),
        ),
    ]
