# Generated by Django 4.2.7 on 2023-11-30 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tune', '0012_alter_tune_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
