# Generated by Django 4.2.7 on 2023-12-07 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0016_repertoiretune_last_played"),
    ]

    operations = [
        migrations.RenameField(
            model_name="repertoiretune",
            old_name="rep_tune",
            new_name="tune",
        ),
    ]
