# Generated by Django 4.2.7 on 2023-12-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0017_rename_rep_tune_repertoiretune_tune"),
    ]

    operations = [
        migrations.AddField(
            model_name="repertoiretune",
            name="knowledge",
            field=models.CharField(
                choices=[("know", "know"), ("learning", "learning"), ("don't know", "don't know")],
                default="know",
                max_length=15,
            ),
        ),
    ]
