# Generated by Django 4.2.7 on 2023-12-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0018_repertoiretune_knowledge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repertoiretune",
            name="knowledge",
            field=models.CharField(
                blank=True,
                choices=[("know", "know"), ("learning", "learning"), ("don't know", "don't know")],
                default="know",
                max_length=15,
                null=True,
            ),
        ),
    ]
