# Generated by Django 4.2.7 on 2023-12-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0020_alter_repertoiretune_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repertoiretune",
            options={},
        ),
        migrations.AlterField(
            model_name="tune",
            name="key",
            field=models.CharField(
                blank=True, help_text="Letters A-G, one only, add - for minor", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="tune",
            name="other_keys",
            field=models.CharField(
                blank=True,
                help_text="Letters A-G, as many as you want, separated by a space",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tune",
            name="song_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aaba", "AABA"),
                    ("abac", "ABAC"),
                    ("aba", "ABA"),
                    ("abab", "ABAB"),
                    ("abcd", "ABCD"),
                    ("aab", "AAB"),
                    ("blues", "blues"),
                    ("irregular", "irregular"),
                ],
                max_length=15,
            ),
        ),
    ]
