# Generated by Django 4.2.7 on 2023-12-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0021_alter_repertoiretune_options_alter_tune_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repertoiretune",
            name="started_learning",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
