# Generated by Django 4.2.7 on 2023-12-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0022_repertoiretune_started_learning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tune",
            name="song_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AABA", "AABA"),
                    ("ABAC", "ABAC"),
                    ("ABA", "ABA"),
                    ("ABAB", "ABAB"),
                    ("ABCD", "ABCD"),
                    ("AAB", "AAB"),
                    ("blues", "blues"),
                    ("irregular", "irregular"),
                ],
                max_length=15,
            ),
        ),
    ]
