# Generated by Django 4.2.7 on 2024-01-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0024_alter_tune_meter"),
    ]

    operations = [
        migrations.AddField(
            model_name="tune",
            name="is_ballad",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="tune",
            name="is_contrafact",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
