# Generated by Django 4.2.7 on 2024-01-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0025_tune_is_ballad_tune_is_contrafact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tune",
            name="title",
            field=models.CharField(help_text="The only required field", max_length=100),
        ),
    ]
