# Generated by Django 4.2.7 on 2024-01-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0026_alter_tune_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name="tune",
            name="song_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AABA", "AABA"),
                    ("ABAC", "ABAC"),
                    ("ABA", "ABA"),
                    ("ABAB", "ABAB"),
                    ("ABCD", "ABCD"),
                    ("AB", "AB"),
                    ("AAB", "AAB"),
                    ("AABC", "AABC"),
                    ("blues", "blues"),
                    ("irregular", "irregular"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="tune",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="tune.tag"),
        ),
    ]
