# Generated by Django 4.2.7 on 2024-01-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0027_tag_alter_tune_song_form_tune_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
