# Generated by Django 4.2.7 on 2024-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0028_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tune",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="tags", to="tune.tag"),
        ),
    ]
