# Generated by Django 4.2.7 on 2024-01-24 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0029_alter_tune_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tune",
            name="is_ballad",
        ),
    ]
