# Generated by Django 4.2.7 on 2024-01-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0032_alter_repertoiretune_knowledge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tune",
            name="title",
            field=models.CharField(help_text="The only required field", max_length=90),
        ),
    ]
