# Generated by Django 5.0.2 on 2024-02-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0033_alter_tune_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repertoiretune",
            name="last_played",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tune",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="(feature under construction)",
                related_name="tags",
                to="tune.tag",
            ),
        ),
    ]
