# Generated by Django 5.0.2 on 2024-03-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0034_alter_repertoiretune_last_played_alter_tune_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="repertoiretune",
            name="play_count",
            field=models.IntegerField(default=0),
        ),
    ]
