# Generated by Django 5.0.3 on 2024-04-11 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0035_repertoiretune_play_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tune",
            name="is_contrafact",
        ),
    ]
