# Generated by Django 5.0.3 on 2024-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tune", "0036_remove_tune_is_contrafact"),
    ]

    operations = [
        migrations.AddField(
            model_name="tune",
            name="is_contrafact",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
